### ISSUE TITLE
Use S4B icon in posts created by plugin

### ISSUE THREAD

**Issue by jasonblais** [kosgrz/mattermost-plugin-skype4business#4]
Observed:

![image](https://user-images.githubusercontent.com/13119842/57961994-ec102800-78e0-11e9-83c7-3f27e62c27f7.png)

Proposed change: When a message is posted by the plugin, use the same Skype4Business icon as used elsewhere in the UI

Below is an example from the Zoom plugin

![image](https://user-images.githubusercontent.com/13119842/57961983-de5aa280-78e0-11e9-9c82-6ed3f999b349.png)

**Comment by jasonblais** [comment]
Related question - does our use of the Skype icon follow their brand guidelines, do you know? 

https://www.skype.com/en/legal/brand-guidelines/

**Comment by kosgrz** [comment]
> Related question - does our use of the Skype icon follow their brand guidelines, do you know?

@jasonblais I'm not sure yet. I've just sent them a question about that via email. After I receive a positive response from them, I will implement your proposed change.
