### ISSUE TITLE
When the meeting ends, update S4B meeting post to say so

### ISSUE THREAD

**Issue by jasonblais** [kosgrz/mattermost-plugin-skype4business#5]
Observed: After ending the meeting, the plugin still says the meeting was started

![image](https://user-images.githubusercontent.com/13119842/57962069-79537c80-78e1-11e9-90fe-0c91d0275b03.png)

Proposed: Example from Zoom plugin below. It is okay to use a simpler version in the S4B plugin such as

```
<user> has ended the meeting

Skype for Business Meeting

Date: <Date> at <Time>
```

![image](https://user-images.githubusercontent.com/13119842/57962057-5923bd80-78e1-11e9-9f84-fbf45a7a4c53.png)

**Comment by kosgrz** [comment]
@jasonblais Unfortunately, this is not possible in S4B. According to the [documentation](https://docs.microsoft.com/en-us/skype-sdk/ucwa/myonlinemeeting_ref), a meeting object doesn't have any fields like "status". There is no way to determine whether a meeting is ended or not. I tried a few days to find a solution but without any results :(

**Comment by jasonblais** [comment]
Ah I see. From reading the documentation I don't really have other ideas either. What's there now is good and we can always adjust based on user feedback 👍 

Closing for now.
